require("dotenv").config();

module.exports = {
  PRODUCT_CATEGORY_ARRAY: [
    "Devotional",
    "Christian Life",
    "Bible Study",
    "Ministry and Evangelism",
    "Music and Hymns",
    "History & Biography",
    "Christian Education",
    "Children Books",
    "Young Adult",
  ],

  BIBLE_TITLE_ARRAY: [
    "Genesis",
    "Exodus",
    "Leviticus",
    "Numbers",
    "Deuteronomy",
    "Joshua",
    "Judges",
    "Ruth",
    "1 Samuel",
    "2 Samuel",
    "1 Kings",
    "2 Kings",
    "1 Chronicles",
    "2 Chronicles",
    "Ezra",
    "Nehemiah",
    "Esther",
    "Job",
    "Psalms",
    "Proverbs",
    "Ecclesiastes",
    "Song of Solomon",
    "Isaiah",
    "Jeremiah",
    "Lamentations",
    "Ezekiel",
    "Daniel",
    "Hosea",
    "Joel",
    "Amos",
    "Obadiah",
    "Jonah",
    "Micah",
    "Nahum",
    "Habakkuk",
    "Zephaniah",
    "Haggai",
    "Zechariah",
    "Malachi",
    "Matthew",
    "Mark",
    "Luke",
    "John",
    "Acts",
    "Romans",
    "1 Corinthians",
    "2 Corinthians",
    "Galatians",
    "Ephesians",
    "Philippians",
    "Colossians",
    "1 Thessalonians",
    "2 Thessalonians",
    "1 Timothy",
    "2 Timothy",
    "Titus",
    "Philemon",
    "Hebrew",
    "James",
    "1 Peter",
    "2 Peter",
    "1 John",
    "2 John",
    "3 John",
    "Jude",
    "Revelation",
  ],

  SITUATION_COLOUR_ARRAY: [
    "bg-orange-1 color-orange",
    "bg-red-1 color-red",
    "bg-pink-1 color-pink",
    "bg-purple-1 color-purple",
    "bg-yellow-1 color-yellow",
    "bg-blue-1 color-blue",
    "bg-snow text-dark",
    "bg-green-1 color-green",
    "bg-cyan-1 color-cyan",
  ],

  CAREER_FIELD_ARRAY: [
    "Education and Training",
    "Ministering, Counselling, Clergy",
    "Business Management and Administration",
    "Arts, Audio/Video Technology and Communications",
    "Finance",
    "Government and Public Administration",
    "Health Science",
    "Hospitality and Tourism",
    "Human Services",
    "Information Technology",
    "Law, Public Safety, Corrections and Security",
    "Manufacturing",
    "Marketing, Sales and Service",
    "Science, Technology, Engineering and Mathematics",
    "Transportation, Distribution and Logistics",
  ],

  USER_ROLE_ARRAY: ["User", "Editor", "Merchant", "Admin", "SuperAdmin"],
};
